import { toolCategories } from './toolCategories';

const makeTool = ({
  id,
  slug,
  name,
  description,
  category,
  sourceEndpoint = null,
  uploadMode = 'single',
  acceptedTypes = ['application/pdf'],
}) => ({
  id,
  slug,
  name,
  description,
  category,
  sourceEndpoint,
  nextEndpoint: `/api/tools/${id}`,
  uploadMode,
  acceptedTypes,
  seoTitle: `${name} Online`,
  seoDescription: `${description}. Use PDFForge to ${name.toLowerCase()} online with a fast browser-based workflow and secure server processing.`,
  relatedTools: [],
});

export const toolRegistry = [
  makeTool({
    id: 'pdfTextEditor',
    slug: 'pdf-text-editor',
    name: 'PDF Text Editor',
    description: 'Review and edit text and images in PDFs',
    category: toolCategories.recommended.id,
    sourceEndpoint: 'text-editor-pdf',
  }),
  makeTool({
    id: 'multiTool',
    slug: 'pdf-tools',
    name: 'Multi-Tool',
    description: 'Use multiple PDF tools on a single document',
    category: toolCategories.automationProduct.id,
    uploadMode: 'multiple',
    sourceEndpoint: 'multi-tool',
  }),
  makeTool({
    id: 'merge',
    slug: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Merge multiple PDFs into a single document',
    category: toolCategories.pageStructure.id,
    uploadMode: 'multiple',
    sourceEndpoint: 'merge-pdfs',
  }),
  makeTool({
    id: 'certSign',
    slug: 'certificate-sign-pdf',
    name: 'Certificate Sign PDF',
    description: 'Sign PDF documents using digital certificates',
    category: toolCategories.securitySigning.id,
    sourceEndpoint: 'cert-sign',
  }),
  makeTool({
    id: 'timestampPdf',
    slug: 'timestamp-pdf',
    name: 'Timestamp PDF',
    description: 'Add a document timestamp to prove when your PDF existed',
    category: toolCategories.securitySigning.id,
    sourceEndpoint: 'timestamp-pdf',
  }),
  makeTool({
    id: 'sign',
    slug: 'sign-pdf',
    name: 'Sign PDF',
    description: 'Add a signature to a PDF by drawing, typing, or uploading an image',
    category: toolCategories.contentEditing.id,
    sourceEndpoint: 'sign',
  }),
  makeTool({
    id: 'addText',
    slug: 'add-text-to-pdf',
    name: 'Add Text to PDF',
    description: 'Add custom text anywhere in your PDF',
    category: toolCategories.contentEditing.id,
    sourceEndpoint: 'sign',
  }),
  makeTool({
    id: 'addImage',
    slug: 'add-image-to-pdf',
    name: 'Add Image to PDF',
    description: 'Add images anywhere in your PDF',
    category: toolCategories.contentEditing.id,
    uploadMode: 'multiple',
    sourceEndpoint: 'add-image',
  }),
  makeTool({
    id: 'annotate',
    slug: 'annotate-pdf',
    name: 'Annotate PDF',
    description: 'Markup, highlight, and annotate PDF documents',
    category: toolCategories.contentEditing.id,
    sourceEndpoint: 'annotate',
  }),
  makeTool({
    id: 'addPassword',
    slug: 'password-protect-pdf',
    name: 'Password Protect PDF',
    description: 'Add password protection and encryption to a PDF',
    category: toolCategories.securitySigning.id,
    sourceEndpoint: 'add-password',
  }),
  makeTool({
    id: 'watermark',
    slug: 'watermark-pdf',
    name: 'Add Watermark',
    description: 'Add text or image watermarks to PDF pages',
    category: toolCategories.contentEditing.id,
    sourceEndpoint: 'add-watermark',
  }),
  makeTool({
    id: 'addStamp',
    slug: 'stamp-pdf',
    name: 'Add Stamp',
    description: 'Stamp PDF pages with reusable text or image stamps',
    category: toolCategories.contentEditing.id,
    sourceEndpoint: 'add-stamp',
  }),
  makeTool({
    id: 'sanitize',
    slug: 'sanitize-pdf',
    name: 'Sanitize PDF',
    description: 'Remove hidden data, scripts, and unsafe content from PDFs',
    category: toolCategories.securitySigning.id,
    sourceEndpoint: 'sanitize-pdf',
  }),
  makeTool({
    id: 'flatten',
    slug: 'flatten-pdf',
    name: 'Flatten PDF',
    description: 'Flatten forms and annotations into regular PDF page content',
    category: toolCategories.formsMetadata.id,
    sourceEndpoint: 'flatten',
  }),
  makeTool({
    id: 'unlockPDFForms',
    slug: 'unlock-pdf-forms',
    name: 'Unlock PDF Forms',
    description: 'Unlock PDF form fields so they can be edited or filled',
    category: toolCategories.formsMetadata.id,
    sourceEndpoint: 'unlock-pdf-forms',
  }),
  makeTool({
    id: 'formFill',
    slug: 'fill-pdf-form',
    name: 'Fill PDF Form',
    description: 'Fill out PDF forms online and export completed documents',
    category: toolCategories.formsMetadata.id,
    sourceEndpoint: 'form-fill',
  }),
  makeTool({
    id: 'changePermissions',
    slug: 'change-pdf-permissions',
    name: 'Change PDF Permissions',
    description: 'Change printing, copying, editing, and security permissions',
    category: toolCategories.securitySigning.id,
    sourceEndpoint: 'change-permissions',
  }),
  makeTool({
    id: 'getPdfInfo',
    slug: 'pdf-info',
    name: 'PDF Info',
    description: 'View page count, metadata, file details, and PDF properties',
    category: toolCategories.formsMetadata.id,
    sourceEndpoint: 'get-info-on-pdf',
  }),
  makeTool({
    id: 'validateSignature',
    slug: 'validate-pdf-signature',
    name: 'Validate PDF Signature',
    description: 'Validate digital signatures and certificate information in PDF files',
    category: toolCategories.securitySigning.id,
    sourceEndpoint: 'validate-signature',
  }),
  makeTool({
    id: 'changeMetadata',
    slug: 'edit-pdf-metadata',
    name: 'Edit PDF Metadata',
    description: 'Change PDF title, author, subject, keywords, and metadata fields',
    category: toolCategories.formsMetadata.id,
    sourceEndpoint: 'update-metadata',
  }),
  makeTool({
    id: 'editTableOfContents',
    slug: 'edit-pdf-table-of-contents',
    name: 'Edit PDF Table of Contents',
    description: 'Create and edit PDF bookmarks, outlines, and table of contents entries',
    category: toolCategories.formsMetadata.id,
    sourceEndpoint: 'edit-table-of-contents',
  }),
  makeTool({
    id: 'crop',
    slug: 'crop-pdf',
    name: 'Crop PDF',
    description: 'Crop PDF pages and adjust visible page boundaries',
    category: toolCategories.pageStructure.id,
    sourceEndpoint: 'crop',
  }),
  makeTool({
    id: 'rotate',
    slug: 'rotate-pdf',
    name: 'Rotate PDF',
    description: 'Rotate one page, selected pages, or every page in a PDF',
    category: toolCategories.pageStructure.id,
    sourceEndpoint: 'rotate-pdf',
  }),
  makeTool({
    id: 'split',
    slug: 'split-pdf',
    name: 'Split PDF',
    description: 'Split PDF files by page ranges, chapters, sections, or size',
    category: toolCategories.pageStructure.id,
    sourceEndpoint: 'split-pdf-by-sections',
  }),
  makeTool({
    id: 'reorganizePages',
    slug: 'reorganize-pdf-pages',
    name: 'Reorganize PDF Pages',
    description: 'Arrange, reorder, duplicate, and organize PDF pages',
    category: toolCategories.pageStructure.id,
    sourceEndpoint: 'rearrange-pages',
  }),
  makeTool({
    id: 'scalePages',
    slug: 'scale-pdf-pages',
    name: 'Scale PDF Pages',
    description: 'Resize, scale, and adjust PDF page dimensions',
    category: toolCategories.pageStructure.id,
    sourceEndpoint: 'scale-pages',
  }),
  makeTool({
    id: 'addPageNumbers',
    slug: 'add-page-numbers-to-pdf',
    name: 'Add Page Numbers',
    description: 'Add customizable page numbers to PDF files',
    category: toolCategories.contentEditing.id,
    sourceEndpoint: 'add-page-numbers',
  }),
  makeTool({
    id: 'pageLayout',
    slug: 'pdf-page-layout',
    name: 'PDF Page Layout',
    description: 'Change PDF page layout and combine pages onto sheets',
    category: toolCategories.pageStructure.id,
    sourceEndpoint: 'multi-page-layout',
  }),
  makeTool({
    id: 'bookletImposition',
    slug: 'booklet-pdf',
    name: 'Booklet PDF',
    description: 'Create printable booklet layouts from PDF documents',
    category: toolCategories.pageStructure.id,
    sourceEndpoint: 'booklet-imposition',
  }),
  makeTool({
    id: 'pdfToSinglePage',
    slug: 'pdf-to-single-page',
    name: 'PDF To Single Page',
    description: 'Convert multi-page PDFs into one long single-page PDF',
    category: toolCategories.pageStructure.id,
    sourceEndpoint: 'pdf-to-single-page',
  }),
  makeTool({
    id: 'addAttachments',
    slug: 'add-attachments-to-pdf',
    name: 'Add Attachments To PDF',
    description: 'Embed file attachments inside PDF documents',
    category: toolCategories.formsMetadata.id,
    uploadMode: 'multiple',
    sourceEndpoint: 'add-attachments',
  }),
  makeTool({
    id: 'extractPages',
    slug: 'extract-pdf-pages',
    name: 'Extract PDF Pages',
    description: 'Extract selected pages from a PDF into a new document',
    category: toolCategories.pageStructure.id,
    sourceEndpoint: 'extract-pages',
  }),
  makeTool({
    id: 'extractImages',
    slug: 'extract-images-from-pdf',
    name: 'Extract Images From PDF',
    description: 'Extract embedded images from PDF files',
    category: toolCategories.conversionOcr.id,
    sourceEndpoint: 'extract-images',
  }),
  makeTool({
    id: 'removePages',
    slug: 'remove-pdf-pages',
    name: 'Remove PDF Pages',
    description: 'Delete selected pages from a PDF document',
    category: toolCategories.pageStructure.id,
    sourceEndpoint: 'remove-pages',
  }),
  makeTool({
    id: 'removeBlanks',
    slug: 'remove-blank-pages-from-pdf',
    name: 'Remove Blank Pages From PDF',
    description: 'Detect and remove blank pages from PDF files',
    category: toolCategories.pageStructure.id,
    sourceEndpoint: 'remove-blanks',
  }),
  makeTool({
    id: 'removeAnnotations',
    slug: 'remove-pdf-annotations',
    name: 'Remove PDF Annotations',
    description: 'Remove annotations, comments, and markups from PDF files',
    category: toolCategories.contentEditing.id,
    sourceEndpoint: 'remove-annotations',
  }),
  makeTool({
    id: 'removeImage',
    slug: 'remove-images-from-pdf',
    name: 'Remove Images From PDF',
    description: 'Remove images and scanned image content from PDFs',
    category: toolCategories.contentEditing.id,
    sourceEndpoint: 'remove-images',
  }),
  makeTool({
    id: 'removePassword',
    slug: 'remove-pdf-password',
    name: 'Remove PDF Password',
    description: 'Remove password protection from PDFs you can open',
    category: toolCategories.securitySigning.id,
    sourceEndpoint: 'remove-password',
  }),
  makeTool({
    id: 'overlayPdfs',
    slug: 'overlay-pdf',
    name: 'Overlay PDF',
    description: 'Overlay one PDF on top of another PDF',
    category: toolCategories.pageStructure.id,
    uploadMode: 'multiple',
    sourceEndpoint: 'overlay-pdfs',
  }),
  makeTool({
    id: 'scannerImageSplit',
    slug: 'split-scanned-pdf',
    name: 'Split Scanned PDF',
    description: 'Split scanned PDF pages into separate documents or sections',
    category: toolCategories.conversionOcr.id,
    sourceEndpoint: 'scanner-image-split',
  }),
  makeTool({
    id: 'adjustContrast',
    slug: 'adjust-pdf-contrast',
    name: 'Adjust PDF Contrast',
    description: 'Improve PDF readability by adjusting contrast and image appearance',
    category: toolCategories.conversionOcr.id,
    sourceEndpoint: 'adjust-contrast',
  }),
  makeTool({
    id: 'replaceColor',
    slug: 'replace-pdf-colors',
    name: 'Replace PDF Colors',
    description: 'Replace, invert, or adjust colors in PDF documents',
    category: toolCategories.conversionOcr.id,
    sourceEndpoint: 'replace-and-invert-color',
  }),
  makeTool({
    id: 'ocr',
    slug: 'ocr-pdf',
    name: 'OCR PDF',
    description: 'Recognize text in scanned PDFs and make documents searchable',
    category: toolCategories.conversionOcr.id,
    sourceEndpoint: 'ocr-pdf',
  }),
  makeTool({
    id: 'convert',
    slug: 'convert-pdf',
    name: 'Convert PDF',
    description: 'Convert PDFs to and from Office, images, HTML, EPUB, and other formats',
    category: toolCategories.conversionOcr.id,
    sourceEndpoint: 'convert',
  }),
  makeTool({
    id: 'compress',
    slug: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce PDF file size while preserving readable quality',
    category: toolCategories.conversionOcr.id,
    sourceEndpoint: 'compress-pdf',
  }),
  makeTool({
    id: 'repair',
    slug: 'repair-pdf',
    name: 'Repair PDF',
    description: 'Repair damaged, malformed, or hard-to-open PDF files',
    category: toolCategories.conversionOcr.id,
    sourceEndpoint: 'repair',
  }),
  makeTool({
    id: 'redact',
    slug: 'redact-pdf',
    name: 'Redact PDF',
    description: 'Permanently redact sensitive text and areas from PDF documents',
    category: toolCategories.securitySigning.id,
    sourceEndpoint: 'redact',
  }),
  makeTool({
    id: 'removeCertSign',
    slug: 'remove-pdf-certificate-signature',
    name: 'Remove Certificate Signature',
    description: 'Remove certificate signature data from PDF documents',
    category: toolCategories.securitySigning.id,
    sourceEndpoint: 'remove-cert-sign',
  }),
  makeTool({
    id: 'autoRename',
    slug: 'auto-rename-pdf',
    name: 'Auto Rename PDF',
    description: 'Automatically rename PDF files based on document content',
    category: toolCategories.automationProduct.id,
    sourceEndpoint: 'auto-rename',
  }),
  makeTool({
    id: 'scannerEffect',
    slug: 'scanner-effect-pdf',
    name: 'Scanner Effect PDF',
    description: 'Apply scanner-style image effects to PDF pages',
    category: toolCategories.conversionOcr.id,
    sourceEndpoint: 'scanner-effect',
  }),
  makeTool({
    id: 'compare',
    slug: 'compare-pdfs',
    name: 'Compare PDFs',
    description: 'Compare two PDF files and review visual or content differences',
    category: toolCategories.conversionOcr.id,
    uploadMode: 'multiple',
    sourceEndpoint: 'compare',
  }),
  makeTool({
    id: 'showJS',
    slug: 'show-pdf-javascript',
    name: 'Show PDF JavaScript',
    description: 'Inspect JavaScript embedded inside PDF files',
    category: toolCategories.formsMetadata.id,
    sourceEndpoint: 'show-javascript',
  }),
  makeTool({
    id: 'read',
    slug: 'read-pdf',
    name: 'Read PDF',
    description: 'Open and read PDF documents in the browser',
    category: toolCategories.automationProduct.id,
    sourceEndpoint: 'read',
  }),
  makeTool({
    id: 'automate',
    slug: 'automate-pdf',
    name: 'Automate PDF',
    description: 'Build reusable PDF workflows that run multiple tools in sequence',
    category: toolCategories.automationProduct.id,
    uploadMode: 'multiple',
    sourceEndpoint: 'automate',
  }),
  makeTool({
    id: 'devApi',
    slug: 'pdf-api',
    name: 'PDF API',
    description: 'Use PDFForge PDF tools through backend API endpoints',
    category: toolCategories.automationProduct.id,
    acceptedTypes: [],
    sourceEndpoint: 'dev-api',
  }),
  makeTool({
    id: 'devFolderScanning',
    slug: 'folder-scanning',
    name: 'Folder Scanning',
    description: 'Monitor folders and process PDF files automatically',
    category: toolCategories.automationProduct.id,
    acceptedTypes: [],
    sourceEndpoint: 'folder-scanning',
  }),
  makeTool({
    id: 'devSsoGuide',
    slug: 'sso-guide',
    name: 'SSO Guide',
    description: 'Configure single sign-on for PDFForge deployments',
    category: toolCategories.automationProduct.id,
    acceptedTypes: [],
    sourceEndpoint: 'sso-guide',
  }),
  makeTool({
    id: 'devAirgapped',
    slug: 'air-gapped-pdf-tools',
    name: 'Air-Gapped PDF Tools',
    description: 'Deploy PDF tools in offline or restricted network environments',
    category: toolCategories.automationProduct.id,
    acceptedTypes: [],
    sourceEndpoint: 'air-gapped',
  }),
];

export const toolsBySlug = new Map(toolRegistry.map((tool) => [tool.slug, tool]));
export const toolsById = new Map(toolRegistry.map((tool) => [tool.id, tool]));

export const getToolBySlug = (slug) => toolsBySlug.get(slug);
export const getToolById = (id) => toolsById.get(id);

export const getToolsByCategory = () =>
  toolRegistry.reduce((groups, tool) => {
    if (!groups[tool.category]) {
      groups[tool.category] = [];
    }
    groups[tool.category].push(tool);
    return groups;
  }, {});
