import { toolCategories } from './toolCategories';

const makeTool = ({
  id,
  slug,
  name,
  description,
  category,
  sourceEndpoint = null,
  uploadMode = 'single',
  acceptedTypes = ['application/pdf'],
}) => ({
  id,
  slug,
  name,
  description,
  category,
  sourceEndpoint,
  nextEndpoint: `/api/tools/${id}`,
  uploadMode,
  acceptedTypes,
  seoTitle: `${name} Online`,
  seoDescription: `${description}. Use PDFForge to ${name.toLowerCase()} online with a fast browser-based workflow and secure server processing.`,
  relatedTools: [],
});

export const toolRegistry = [
  makeTool({
    id: 'pdfTextEditor',
    slug: 'visual-text-editor',
    name: 'Visual Text Editor',
    description: 'Review and edit text and images in PDFs',
    category: toolCategories.recommended.id,
    sourceEndpoint: 'text-editor-pdf',
  }),
  makeTool({
    id: 'multiTool',
    slug: 'chained-actions',
    name: 'Chained Actions',
    description: 'Use multiple PDF tools on a single document',
    category: toolCategories.automationProduct.id,
    uploadMode: 'multiple',
    sourceEndpoint: 'multi-tool',
  }),
  makeTool({
    id: 'merge',
    slug: 'merge-documents',
    name: 'Merge Documents',
    description: 'Merge multiple PDFs into a single document',
    category: toolCategories.pageStructure.id,
    uploadMode: 'multiple',
    sourceEndpoint: 'merge-pdfs',
  }),
  makeTool({
    id: 'certSign',
    slug: 'certificate-signing',
    name: 'Certificate Signing',
    description: 'Sign PDF documents using digital certificates',
    category: toolCategories.securitySigning.id,
    sourceEndpoint: 'cert-sign',
  }),
  makeTool({
    id: 'timestampPdf',
    slug: 'document-timestamps',
    name: 'Document Timestamps',
    description: 'Add a document timestamp to prove when your PDF existed',
    category: toolCategories.securitySigning.id,
    sourceEndpoint: 'timestamp-pdf',
  }),
  makeTool({
    id: 'sign',
    slug: 'add-signature',
    name: 'Add Signature',
    description: 'Add a signature to a PDF by drawing, typing, or uploading an image',
    category: toolCategories.contentEditing.id,
    sourceEndpoint: 'sign',
  }),
  makeTool({
    id: 'addText',
    slug: 'insert-text',
    name: 'Insert Text',
    description: 'Add custom text anywhere in your PDF',
    category: toolCategories.contentEditing.id,
    sourceEndpoint: 'sign',
  }),
  makeTool({
    id: 'addImage',
    slug: 'insert-images',
    name: 'Insert Images',
    description: 'Add images anywhere in your PDF',
    category: toolCategories.contentEditing.id,
    uploadMode: 'multiple',
    sourceEndpoint: 'add-image',
  }),
  makeTool({
    id: 'annotate',
    slug: 'markup-pages',
    name: 'Markup Pages',
    description: 'Markup, highlight, and annotate PDF documents',
    category: toolCategories.contentEditing.id,
    sourceEndpoint: 'annotate',
  }),
  makeTool({
    id: 'addPassword',
    slug: 'secure-document',
    name: 'Secure Document',
    description: 'Add password protection and encryption to a PDF',
    category: toolCategories.securitySigning.id,
    sourceEndpoint: 'add-password',
  }),
  makeTool({
    id: 'watermark',
    slug: 'apply-watermark',
    name: 'Apply Watermark',
    description: 'Add text or image watermarks to PDF pages',
    category: toolCategories.contentEditing.id,
    sourceEndpoint: 'add-watermark',
  }),
  makeTool({
    id: 'addStamp',
    slug: 'apply-stamp',
    name: 'Apply Stamp',
    description: 'Stamp PDF pages with reusable text or image stamps',
    category: toolCategories.contentEditing.id,
    sourceEndpoint: 'add-stamp',
  }),
  makeTool({
    id: 'sanitize',
    slug: 'clean-content',
    name: 'Clean Content',
    description: 'Remove hidden data, scripts, and unsafe content from PDFs',
    category: toolCategories.securitySigning.id,
    sourceEndpoint: 'sanitize-pdf',
  }),
  makeTool({
    id: 'flatten',
    slug: 'flatten-forms',
    name: 'Flatten Forms',
    description: 'Flatten forms and annotations into regular PDF page content',
    category: toolCategories.formsMetadata.id,
    sourceEndpoint: 'flatten',
  }),
  makeTool({
    id: 'unlockPDFForms',
    slug: 'enable-form-fields',
    name: 'Enable Form Fields',
    description: 'Unlock PDF form fields so they can be edited or filled',
    category: toolCategories.formsMetadata.id,
    sourceEndpoint: 'unlock-pdf-forms',
  }),
  makeTool({
    id: 'formFill',
    slug: 'fill-form',
    name: 'Fill Form',
    description: 'Fill out PDF forms online and export completed documents',
    category: toolCategories.formsMetadata.id,
    sourceEndpoint: 'form-fill',
  }),
  makeTool({
    id: 'changePermissions',
    slug: 'manage-access',
    name: 'Manage Access',
    description: 'Change printing, copying, editing, and security permissions',
    category: toolCategories.securitySigning.id,
    sourceEndpoint: 'change-permissions',
  }),
  makeTool({
    id: 'getPdfInfo',
    slug: 'document-details',
    name: 'Document Details',
    description: 'View page count, metadata, file details, and PDF properties',
    category: toolCategories.formsMetadata.id,
    sourceEndpoint: 'get-info-on-pdf',
  }),
  makeTool({
    id: 'validateSignature',
    slug: 'verify-signatures',
    name: 'Verify Signatures',
    description: 'Validate digital signatures and certificate information in PDF files',
    category: toolCategories.securitySigning.id,
    sourceEndpoint: 'validate-signature',
  }),
  makeTool({
    id: 'changeMetadata',
    slug: 'change-properties',
    name: 'Change Properties',
    description: 'Change PDF title, author, subject, keywords, and metadata fields',
    category: toolCategories.formsMetadata.id,
    sourceEndpoint: 'update-metadata',
  }),
  makeTool({
    id: 'editTableOfContents',
    slug: 'manage-bookmarks',
    name: 'Manage Bookmarks',
    description: 'Create and edit PDF bookmarks, outlines, and table of contents entries',
    category: toolCategories.formsMetadata.id,
    sourceEndpoint: 'edit-table-of-contents',
  }),
  makeTool({
    id: 'crop',
    slug: 'crop-pages',
    name: 'Crop Pages',
    description: 'Crop PDF pages and adjust visible page boundaries',
    category: toolCategories.pageStructure.id,
    sourceEndpoint: 'crop',
  }),
  makeTool({
    id: 'rotate',
    slug: 'rotate-pages',
    name: 'Rotate Pages',
    description: 'Rotate one page, selected pages, or every page in a PDF',
    category: toolCategories.pageStructure.id,
    sourceEndpoint: 'rotate-pdf',
  }),
  makeTool({
    id: 'split',
    slug: 'split-files',
    name: 'Split Files',
    description: 'Split PDF files by page ranges, chapters, sections, or size',
    category: toolCategories.pageStructure.id,
    sourceEndpoint: 'split-pdf-by-sections',
  }),
  makeTool({
    id: 'reorganizePages',
    slug: 'reorder-pages',
    name: 'Reorder Pages',
    description: 'Arrange, reorder, duplicate, and organize PDF pages',
    category: toolCategories.pageStructure.id,
    sourceEndpoint: 'rearrange-pages',
  }),
  makeTool({
    id: 'scalePages',
    slug: 'resize-pages',
    name: 'Resize Pages',
    description: 'Resize, scale, and adjust PDF page dimensions',
    category: toolCategories.pageStructure.id,
    sourceEndpoint: 'scale-pages',
  }),
  makeTool({
    id: 'addPageNumbers',
    slug: 'page-numbering',
    name: 'Page Numbering',
    description: 'Add customizable page numbers to PDF files',
    category: toolCategories.contentEditing.id,
    sourceEndpoint: 'add-page-numbers',
  }),
  makeTool({
    id: 'pageLayout',
    slug: 'page-layouts',
    name: 'Page Layouts',
    description: 'Change PDF page layout and combine pages onto sheets',
    category: toolCategories.pageStructure.id,
    sourceEndpoint: 'multi-page-layout',
  }),
  makeTool({
    id: 'bookletImposition',
    slug: 'booklet-creator',
    name: 'Booklet Creator',
    description: 'Create printable booklet layouts from PDF documents',
    category: toolCategories.pageStructure.id,
    sourceEndpoint: 'booklet-imposition',
  }),
  makeTool({
    id: 'pdfToSinglePage',
    slug: 'one-page-view',
    name: 'One-Page View',
    description: 'Convert multi-page PDFs into one long single-page PDF',
    category: toolCategories.pageStructure.id,
    sourceEndpoint: 'pdf-to-single-page',
  }),
  makeTool({
    id: 'addAttachments',
    slug: 'embed-files',
    name: 'Embed Files',
    description: 'Embed file attachments inside PDF documents',
    category: toolCategories.formsMetadata.id,
    uploadMode: 'multiple',
    sourceEndpoint: 'add-attachments',
  }),
  makeTool({
    id: 'extractPages',
    slug: 'extract-pages',
    name: 'Extract Pages',
    description: 'Extract selected pages from a PDF into a new document',
    category: toolCategories.pageStructure.id,
    sourceEndpoint: 'extract-pages',
  }),
  makeTool({
    id: 'extractImages',
    slug: 'pull-images',
    name: 'Pull Images',
    description: 'Extract embedded images from PDF files',
    category: toolCategories.conversionOcr.id,
    sourceEndpoint: 'extract-images',
  }),
  makeTool({
    id: 'removePages',
    slug: 'delete-pages',
    name: 'Delete Pages',
    description: 'Delete selected pages from a PDF document',
    category: toolCategories.pageStructure.id,
    sourceEndpoint: 'remove-pages',
  }),
  makeTool({
    id: 'removeBlanks',
    slug: 'strip-blank-pages',
    name: 'Strip Blank Pages',
    description: 'Detect and remove blank pages from PDF files',
    category: toolCategories.pageStructure.id,
    sourceEndpoint: 'remove-blanks',
  }),
  makeTool({
    id: 'removeAnnotations',
    slug: 'clear-markups',
    name: 'Clear Markups',
    description: 'Remove annotations, comments, and markups from PDF files',
    category: toolCategories.contentEditing.id,
    sourceEndpoint: 'remove-annotations',
  }),
  makeTool({
    id: 'removeImage',
    slug: 'strip-images',
    name: 'Strip Images',
    description: 'Remove images and scanned image content from PDFs',
    category: toolCategories.contentEditing.id,
    sourceEndpoint: 'remove-images',
  }),
  makeTool({
    id: 'removePassword',
    slug: 'remove-protection',
    name: 'Remove Protection',
    description: 'Remove password protection from PDFs you can open',
    category: toolCategories.securitySigning.id,
    sourceEndpoint: 'remove-password',
  }),
  makeTool({
    id: 'overlayPdfs',
    slug: 'layer-documents',
    name: 'Layer Documents',
    description: 'Overlay one PDF on top of another PDF',
    category: toolCategories.pageStructure.id,
    uploadMode: 'multiple',
    sourceEndpoint: 'overlay-pdfs',
  }),
  makeTool({
    id: 'scannerImageSplit',
    slug: 'separate-scans',
    name: 'Separate Scans',
    description: 'Split scanned PDF pages into separate documents or sections',
    category: toolCategories.conversionOcr.id,
    sourceEndpoint: 'scanner-image-split',
  }),
  makeTool({
    id: 'adjustContrast',
    slug: 'enhance-visuals',
    name: 'Enhance Visuals',
    description: 'Improve PDF readability by adjusting contrast and image appearance',
    category: toolCategories.conversionOcr.id,
    sourceEndpoint: 'adjust-contrast',
  }),
  makeTool({
    id: 'replaceColor',
    slug: 'color-settings',
    name: 'Color Settings',
    description: 'Replace, invert, or adjust colors in PDF documents',
    category: toolCategories.conversionOcr.id,
    sourceEndpoint: 'replace-and-invert-color',
  }),
  makeTool({
    id: 'ocr',
    slug: 'text-recognition',
    name: 'Text Recognition',
    description: 'Recognize text in scanned PDFs and make documents searchable',
    category: toolCategories.conversionOcr.id,
    sourceEndpoint: 'ocr-pdf',
  }),
  makeTool({
    id: 'convert',
    slug: 'file-converter',
    name: 'File Converter',
    description: 'Convert PDFs to and from Office, images, HTML, EPUB, and other formats',
    category: toolCategories.conversionOcr.id,
    sourceEndpoint: 'convert',
  }),
  makeTool({
    id: 'compress',
    slug: 'shrink-files',
    name: 'Shrink Files',
    description: 'Reduce PDF file size while preserving readable quality',
    category: toolCategories.conversionOcr.id,
    sourceEndpoint: 'compress-pdf',
  }),
  makeTool({
    id: 'repair',
    slug: 'fix-documents',
    name: 'Fix Documents',
    description: 'Repair damaged, malformed, or hard-to-open PDF files',
    category: toolCategories.conversionOcr.id,
    sourceEndpoint: 'repair',
  }),
  makeTool({
    id: 'redact',
    slug: 'redact-content',
    name: 'Redact Content',
    description: 'Permanently redact sensitive text and areas from PDF documents',
    category: toolCategories.securitySigning.id,
    sourceEndpoint: 'redact',
  }),
  makeTool({
    id: 'removeCertSign',
    slug: 'clear-signatures',
    name: 'Clear Signatures',
    description: 'Remove certificate signature data from PDF documents',
    category: toolCategories.securitySigning.id,
    sourceEndpoint: 'remove-cert-sign',
  }),
  makeTool({
    id: 'autoRename',
    slug: 'smart-renaming',
    name: 'Smart Renaming',
    description: 'Automatically rename PDF files based on document content',
    category: toolCategories.automationProduct.id,
    sourceEndpoint: 'auto-rename',
  }),
  makeTool({
    id: 'scannerEffect',
    slug: 'scan-filters',
    name: 'Scan Filters',
    description: 'Apply scanner-style image effects to PDF pages',
    category: toolCategories.conversionOcr.id,
    sourceEndpoint: 'scanner-effect',
  }),
  makeTool({
    id: 'compare',
    slug: 'compare-files',
    name: 'Compare Files',
    description: 'Compare two PDF files and review visual or content differences',
    category: toolCategories.conversionOcr.id,
    uploadMode: 'multiple',
    sourceEndpoint: 'compare',
  }),
  makeTool({
    id: 'showJS',
    slug: 'inspect-scripts',
    name: 'Inspect Scripts',
    description: 'Inspect JavaScript embedded inside PDF files',
    category: toolCategories.formsMetadata.id,
    sourceEndpoint: 'show-javascript',
  }),
  makeTool({
    id: 'read',
    slug: 'online-reader',
    name: 'Online Reader',
    description: 'Open and read PDF documents in the browser',
    category: toolCategories.automationProduct.id,
    sourceEndpoint: 'read',
  }),
  makeTool({
    id: 'automate',
    slug: 'workflow-builder',
    name: 'Workflow Builder',
    description: 'Build reusable PDF workflows that run multiple tools in sequence',
    category: toolCategories.automationProduct.id,
    uploadMode: 'multiple',
    sourceEndpoint: 'automate',
  }),
  makeTool({
    id: 'devApi',
    slug: 'developer-api',
    name: 'Developer API',
    description: 'Use PDFForge PDF tools through backend API endpoints',
    category: toolCategories.automationProduct.id,
    acceptedTypes: [],
    sourceEndpoint: 'dev-api',
  }),
  makeTool({
    id: 'devFolderScanning',
    slug: 'folder-scanning',
    name: 'Folder Scanning',
    description: 'Monitor folders and process PDF files automatically',
    category: toolCategories.automationProduct.id,
    acceptedTypes: [],
    sourceEndpoint: 'folder-scanning',
  }),
  makeTool({
    id: 'devSsoGuide',
    slug: 'sso-guide',
    name: 'SSO Guide',
    description: 'Configure single sign-on for PDFForge deployments',
    category: toolCategories.automationProduct.id,
    acceptedTypes: [],
    sourceEndpoint: 'sso-guide',
  }),
  makeTool({
    id: 'devAirgapped',
    slug: 'offline-access',
    name: 'Offline Access',
    description: 'Deploy PDF tools in offline or restricted network environments',
    category: toolCategories.automationProduct.id,
    acceptedTypes: [],
    sourceEndpoint: 'air-gapped',
  }),
];

export const toolsBySlug = new Map(toolRegistry.map((tool) => [tool.slug, tool]));
export const toolsById = new Map(toolRegistry.map((tool) => [tool.id, tool]));

export const getToolBySlug = (slug) => toolsBySlug.get(slug);
export const getToolById = (id) => toolsById.get(id);

export const getToolsByCategory = () =>
  toolRegistry.reduce((groups, tool) => {
    if (!groups[tool.category]) {
      groups[tool.category] = [];
    }
    groups[tool.category].push(tool);
    return groups;
  }, {});
